# conda env create environment.yml
# source activate BackupHub
# source deactivate
name: BackupHub
channels:
  - defaults
dependencies:
  - python=3.5
  - pip:
    - python-gitlab>=1.3.0
    - PyGithub==1.26.0
